spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_1?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root123


server:
  servlet:
    session:
      timeout: 1800

gpt:
  code: ""